name: Apenas Hospedar Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar código do repositório
        uses: actions/checkout@v4
